# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Personal Paper"
license = "MIT"
licenselink = "https://github.com/valtlfelipe/hugo-personal-paper/blob/master/LICENSE"
description = "A simple, clean, flexible Hugo theme based on Paper"
homepage = "https://github.com/valtlfelipe/hugo-personal-paper/"
tags = ["Personal", "Responsive", "Simple", "Clean", "Light", "White", "Blog"]
features = ["Responsive", "One Column", "Blog"]
min_version = "0.1"

[author]
  name = "valtlfelipe"
  homepage = "https://felipe.im/"

# If porting an existing theme
[original]
  name = "Paper"
  homepage = "https://github.com/nanxiaobei/hugo-paper"
  repo = "https://github.com/nanxiaobei/hugo-paper"
